# Generated by Django 4.2.6 on 2023-10-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='conten',
            new_name='content',
        ),
    ]
