# Generated by Django 4.2.6 on 2023-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_book_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(to='products.book'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to='products.customer'),
        ),
    ]
